package com.transunion.lfe.ui.repository

import com.amazonaws.services.dynamodbv2.datamodeling.*


@DynamoDBTable(tableName = "surveyInfo")
data class SurveyInfo @JvmOverloads constructor(@DynamoDBHashKey
                                                @DynamoDBAutoGeneratedKey val id : String? = null,
                                                @DynamoDBAttribute(attributeName = "questions") var questions:
                                                List<Question> = mutableListOf())


@DynamoDBDocument
data class Question(@DynamoDBAttribute val question: String,
                    @DynamoDBAttribute val status : String,
                    @DynamoDBAttribute val response : String)