package com.training.survey.repositories

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "question")
data class Question @JvmOverloads constructor(@DynamoDBHashKey
                    @DynamoDBAutoGeneratedKey var id: String = "",
                    @DynamoDBAttribute(attributeName = "question") var question: String = "")